Define "feature macros" for symlink
Define _XOPEN_SOURCE and _POSIX_C_SOURCE appropriately in order to be
able to use functions such as symlink() on cygwin.

Before that it would error while running make about not being able to
find a function called "symlink". After looking into the header files,
I've found it requires at least one of those macros in order to be
defined.

The error was:

g++ -std=c++11 -DHAVE_CONFIG_H -I.     -g -O2 -MT Fileinfo.o -MD -MP -MF .deps/Fileinfo.Tpo -c -o Fileinfo.o Fileinfo.cc
Fileinfo.cc: In lambda function:
Fileinfo.cc:280:14: error: ‘symlink’ was not declared in this scope
       return symlink(target.c_str(), filename.c_str());
              ^~~~~~~
Fileinfo.cc:280:14: note: suggested alternative: ‘unlink’
       return symlink(target.c_str(), filename.c_str());
              ^~~~~~~
              unlink

Additionally, man 2 symlink (on Ubuntu 18.04) says, it'll be defined
for:

    _XOPEN_SOURCE >= 500 || _POSIX_C_SOURCE >= 200112L
        || /* Glibc versions <= 2.19: */ _BSD_SOURCE

However, defining _BSD_SOURCE would cause cygwin sys/feature.h to define
_DEFAULT_SOURCE, which in turns always redefines _POSIX_C_SOURCE,
causing an redefinition warning when the config.h file is processed
again. Thus _BSD_SOURCE isn't defined, for now.

This is also my first time modifying autoconfig files. I hope I did
everything alright.